contrarian_claims_full = {
    1: {"code": "1", "description": "Global warming is not happening"},
    2: {"code": "2", "description": "Human greenhouse gases are not causing climate change"},
    3: {"code": "3", "description": "Climate impacts/global warming is beneficial/not bad"},
    4: {"code": "4", "description": "Climate solutions won't work"},
    5: {"code": "5", "description": "Climate movement/science is unreliable"},
    6: {"code": "1.1", "description": "Ice/permafrost/snow cover isn't melting"},
    7: {"code": "1.1.1", "description": "Antarctica is gaining ice/not warming"},
    8: {"code": "1.1.2", "description": "Greenland is gaining ice/not melting"},
    9: {"code": "1.1.3", "description": "Arctic sea ice isn't vanishing"},
    10: {"code": "1.1.4", "description": "Glaciers aren't vanishing"},
    11: {"code": "1.2", "description": "We're heading into an ice age/global cooling"},
    12: {"code": "1.3", "description": "Weather is cold/snowing"},
    13: {"code": "1.4", "description": "Climate hasn't warmed/changed over the last (few) decade(s)"},
    14: {"code": "1.5", "description": "Oceans are cooling/not warming"},
    15: {"code": "1.6", "description": "Sea level rise is exaggerated/not accelerating"},
    16: {"code": "1.7", "description": "Extreme weather isn't increasing/has happened before/isn't linked to climate change"},
    17: {"code": "1.8", "description": "They changed the name from 'global warming' to 'climate change'"},
    18: {"code": "2.1", "description": "It's natural cycles/variation"},
    19: {"code": "2.1.1", "description": "It's the sun/cosmic rays/astronomical"},
    20: {"code": "2.1.2", "description": "It's geological (includes volcanoes)"},
    21: {"code": "2.1.3", "description": "It's the ocean/internal variability"},
    22: {"code": "2.1.4", "description": "Climate has changed naturally/been warm in the past"},
    23: {"code": "2.1.5", "description": "Human CO2 emissions are tiny compared to natural CO2 emission"},
    24: {"code": "2.2", "description": "It's non-greenhouse gas human climate forcings (aerosols, land use)"},
    25: {"code": "2.3", "description": "There's no evidence for greenhouse effect/carbon dioxide driving climate change"},
    26: {"code": "2.3.1", "description": "Carbon dioxide is just a trace gas"},
    27: {"code": "2.3.2", "description": "Greenhouse effect is saturated/logarithmic"},
    28: {"code": "2.3.3", "description": "Carbon dioxide lags/not correlated with climate change"},
    29: {"code": "2.3.4", "description": "Water vapor is the most powerful greenhouse gas"},
    30: {"code": "2.3.5", "description": "There's no tropospheric hot spot"},
    31: {"code": "3.1", "description": "Climate sensitivity is low/negative feedbacks reduce warming"},
    32: {"code": "3.2", "description": "Species/plants/reefs aren't showing climate impacts yet/are benefiting from climate change"},
    33: {"code": "3.2.1", "description": "Species can adapt to global warming"},
    34: {"code": "3.2.2", "description": "Polar bears are not in danger from climate change"},
    35: {"code": "3.2.3", "description": "Ocean acidification/coral impacts aren't serious"},
    36: {"code": "3.3", "description": "CO2 is beneficial/not a pollutant"},
    37: {"code": "3.3.1", "description": "CO2 is plant food"},
    38: {"code": "3.4", "description": "It's only a few degrees (or less)"},
    39: {"code": "3.5", "description": "Climate change does not contribute to human conflict/threaten national security"},
    40: {"code": "3.6", "description": "Climate change doesn't negatively impact health"},
    41: {"code": "4.1", "description": "Climate policies (mitigation or adaptation) are harmful"},
    42: {"code": "4.1.1", "description": "Climate policy will increase costs/harm economy/kill jobs"},
    43: {"code": "4.1.2", "description": "Proposed action would weaken national security/national sovereignty/cause conflict"},
    44: {"code": "4.1.3", "description": "Proposed action would actually harm the environment and species"},
    45: {"code": "4.1.4", "description": "Future generations will be richer and better able to adapt"},
    46: {"code": "4.1.5", "description": "Climate policy limits liberty/freedom/capitalism"},
    47: {"code": "4.2", "description": "Climate policies are ineffective/flawed"},
    48: {"code": "4.2.1", "description": "Clean energy/green jobs/businesses won't work"},
    49: {"code": "4.2.2", "description": "Markets/private sector are economically more efficient than government policies"},
    50: {"code": "4.2.3", "description": "Climate policy will make negligible difference to climate change"},
    51: {"code": "4.2.4", "description": "A single country/region only contributes a small % of global emissions"},
    52: {"code": "4.2.5", "description": "Better to adapt/geoengineer/increase resiliency"},
    53: {"code": "4.2.6", "description": "Climate action is pointless because of China/India/other countries' emissions"},
    54: {"code": "4.2.7", "description": "We should invest in technology/reduce poverty/disease first"},
    55: {"code": "4.3", "description": "It's too hard to solve"},
    56: {"code": "4.3.1", "description": "Climate policy is politically/legally/economically/technically too difficult"},
    57: {"code": "4.3.2", "description": "Media/public support/acceptance is low/decreasing"},
    58: {"code": "4.4", "description": "Clean energy technology/biofuels won't work"},
    59: {"code": "4.4.1", "description": "Clean energy/biofuels are too expensive/unreliable/counterproductive/harmful"},
    60: {"code": "4.4.2", "description": "Carbon Capture & Sequestration (CCS) is unproven/expensive"},
    61: {"code": "4.5", "description": "People need energy (e.g., from fossil fuels/nuclear)"},
    62: {"code": "4.5.1", "description": "Fossil fuel reserves are plentiful"},
    63: {"code": "4.5.2", "description": "Fossil fuels are cheap/good/safe for society/economy/environment"},
    64: {"code": "4.5.3", "description": "Nuclear power is safe/good for society/economy/environment"},
    65: {"code": "5.1", "description": "Climate-related science is uncertain/unsound/unreliable (data, methods & models)"},
    66: {"code": "5.1.1", "description": "There's no scientific consensus on climate/the science isn't settled"},
    67: {"code": "5.1.2", "description": "Proxy data is unreliable (includes hockey stick)"},
    68: {"code": "5.1.3", "description": "Temperature record is unreliable"},
    69: {"code": "5.1.4", "description": "Models are wrong/unreliable/uncertain"},
    70: {"code": "5.2", "description": "Climate movement is alarmist/wrong/political/biased/hypocritical (people or groups)"},
    71: {"code": "5.2.1", "description": "Climate movement is religion"},
    72: {"code": "5.2.2", "description": "Media (including bloggers) is alarmist/wrong/political/biased"}
}